-- Migration: Insert 100 sample jewelry products
-- Timestamp: 20260317142000

DO $$
DECLARE
    cat_nhan UUID;
    cat_vong UUID;
    cat_day UUID;
    cat_bong UUID;
    cat_lac UUID;
BEGIN
    -- Fetch existing category IDs by slug
    SELECT id INTO cat_nhan FROM public.categories WHERE slug = 'nhan' OR name_vi ILIKE '%nhẫn%' OR name ILIKE '%ring%' LIMIT 1;
    SELECT id INTO cat_vong FROM public.categories WHERE slug = 'vong' OR name_vi ILIKE '%vòng%' OR name ILIKE '%bracelet%' LIMIT 1;
    SELECT id INTO cat_day FROM public.categories WHERE slug = 'day-chuyen' OR name_vi ILIKE '%dây%' OR name ILIKE '%necklace%' LIMIT 1;
    SELECT id INTO cat_bong FROM public.categories WHERE slug = 'bong-tai' OR name_vi ILIKE '%bông%' OR name ILIKE '%earring%' LIMIT 1;
    SELECT id INTO cat_lac FROM public.categories WHERE slug = 'lac' OR name_vi ILIKE '%lắc%' OR name ILIKE '%anklet%' LIMIT 1;

    -- Fallback: if any category not found, use the first available
    IF cat_nhan IS NULL THEN SELECT id INTO cat_nhan FROM public.categories ORDER BY sort_order LIMIT 1; END IF;
    IF cat_vong IS NULL THEN SELECT id INTO cat_vong FROM public.categories ORDER BY sort_order LIMIT 1; END IF;
    IF cat_day IS NULL THEN SELECT id INTO cat_day FROM public.categories ORDER BY sort_order LIMIT 1; END IF;
    IF cat_bong IS NULL THEN SELECT id INTO cat_bong FROM public.categories ORDER BY sort_order LIMIT 1; END IF;
    IF cat_lac IS NULL THEN SELECT id INTO cat_lac FROM public.categories ORDER BY sort_order LIMIT 1; END IF;

    -- =====================
    -- NHẪN (Rings) - 20 products
    -- =====================
    INSERT INTO public.products (id, category_id, name, name_vi, slug, description, description_vi, price, original_price, image_url, image_alt, sku, stock_quantity, is_active, is_new, is_best_seller, is_featured, material, weight_grams, tags)
    VALUES
    (gen_random_uuid(), cat_nhan, 'Diamond Solitaire Ring', 'Nhẫn Kim Cương Solitaire', 'nhan-kim-cuong-solitaire', 'Elegant solitaire diamond ring set in 18k white gold, perfect for engagements.', 'Nhẫn kim cương solitaire sang trọng được chế tác từ vàng trắng 18k, hoàn hảo cho lễ đính hôn.', 15800000, 18500000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600', 'Nhẫn kim cương solitaire vàng trắng 18k', 'NHN-001', 15, true, true, false, true, 'Vàng trắng 18k, Kim cương', 3.2, ARRAY['nhẫn', 'kim cương', 'đính hôn', 'vàng trắng']),
    (gen_random_uuid(), cat_nhan, 'Rose Gold Heart Ring', 'Nhẫn Vàng Hồng Hình Tim', 'nhan-vang-hong-hinh-tim', 'Romantic heart-shaped rose gold ring adorned with sparkling cubic zirconia.', 'Nhẫn vàng hồng hình trái tim lãng mạn được đính đá cubic zirconia lấp lánh.', 2850000, 3200000, 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600', 'Nhẫn vàng hồng hình tim đính đá', 'NHN-002', 30, true, true, true, false, 'Vàng hồng 14k', 2.8, ARRAY['nhẫn', 'vàng hồng', 'hình tim', 'lãng mạn']),
    (gen_random_uuid(), cat_nhan, 'Sapphire Cluster Ring', 'Nhẫn Đá Sapphire Chùm', 'nhan-da-sapphire-chum', 'Stunning cluster ring featuring deep blue sapphires surrounded by diamonds.', 'Nhẫn chùm ấn tượng với đá sapphire xanh đậm được bao quanh bởi kim cương.', 9500000, 11000000, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600', 'Nhẫn đá sapphire chùm xanh đậm', 'NHN-003', 12, true, false, true, false, 'Vàng vàng 18k, Sapphire, Kim cương', 4.1, ARRAY['nhẫn', 'sapphire', 'chùm', 'xanh']),
    (gen_random_uuid(), cat_nhan, 'Gold Band Ring', 'Nhẫn Vàng Trơn', 'nhan-vang-tron', 'Classic plain gold band, timeless and versatile for everyday wear.', 'Nhẫn vàng trơn cổ điển, thanh lịch và linh hoạt cho việc đeo hàng ngày.', 4200000, NULL, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', 'Nhẫn vàng trơn cổ điển', 'NHN-004', 50, true, false, true, false, 'Vàng vàng 18k', 5.0, ARRAY['nhẫn', 'vàng', 'trơn', 'cổ điển']),
    (gen_random_uuid(), cat_nhan, 'Emerald Cut Engagement Ring', 'Nhẫn Đính Hôn Cắt Emerald', 'nhan-dinh-hon-cat-emerald', 'Sophisticated emerald cut diamond engagement ring in platinum setting.', 'Nhẫn đính hôn kim cương cắt emerald tinh tế trong khung bạch kim.', 22500000, 26000000, 'https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=600', 'Nhẫn đính hôn kim cương cắt emerald bạch kim', 'NHN-005', 8, true, true, false, true, 'Bạch kim, Kim cương', 4.5, ARRAY['nhẫn', 'đính hôn', 'kim cương', 'bạch kim']),
    (gen_random_uuid(), cat_nhan, 'Pearl Cocktail Ring', 'Nhẫn Ngọc Trai Cocktail', 'nhan-ngoc-trai-cocktail', 'Bold cocktail ring featuring a lustrous freshwater pearl centerpiece.', 'Nhẫn cocktail nổi bật với viên ngọc trai nước ngọt óng ánh ở trung tâm.', 3600000, 4100000, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600', 'Nhẫn ngọc trai cocktail sang trọng', 'NHN-006', 20, true, false, false, false, 'Bạc 925, Ngọc trai', 3.8, ARRAY['nhẫn', 'ngọc trai', 'cocktail']),
    (gen_random_uuid(), cat_nhan, 'Twisted Infinity Ring', 'Nhẫn Vô Cực Xoắn', 'nhan-vo-cuc-xoan', 'Delicate twisted infinity ring symbolizing eternal love and connection.', 'Nhẫn vô cực xoắn tinh tế tượng trưng cho tình yêu và sự kết nối vĩnh cửu.', 1950000, 2300000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Nhẫn vô cực xoắn tinh tế', 'NHN-007', 45, true, true, false, false, 'Bạc 925 mạ vàng', 2.1, ARRAY['nhẫn', 'vô cực', 'xoắn', 'tình yêu']),
    (gen_random_uuid(), cat_nhan, 'Ruby Halo Ring', 'Nhẫn Halo Đá Ruby', 'nhan-halo-da-ruby', 'Glamorous halo ring with a vivid red ruby surrounded by sparkling diamonds.', 'Nhẫn halo lộng lẫy với đá ruby đỏ rực được bao quanh bởi kim cương lấp lánh.', 12800000, 15000000, 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600', 'Nhẫn halo đá ruby đỏ và kim cương', 'NHN-008', 10, true, false, true, true, 'Vàng vàng 18k, Ruby, Kim cương', 4.3, ARRAY['nhẫn', 'ruby', 'halo', 'đỏ']),
    (gen_random_uuid(), cat_nhan, 'Stackable Birthstone Ring', 'Nhẫn Đá Sinh Nhật Xếp Chồng', 'nhan-da-sinh-nhat-xep-chong', 'Minimalist stackable ring set with a colorful birthstone of your choice.', 'Nhẫn xếp chồng tối giản được đính đá sinh nhật màu sắc theo lựa chọn của bạn.', 1650000, NULL, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600', 'Nhẫn đá sinh nhật xếp chồng tối giản', 'NHN-009', 60, true, true, false, false, 'Bạc 925', 1.8, ARRAY['nhẫn', 'đá sinh nhật', 'xếp chồng', 'tối giản']),
    (gen_random_uuid(), cat_nhan, 'Vintage Filigree Ring', 'Nhẫn Filigree Cổ Điển', 'nhan-filigree-co-dien', 'Intricate vintage-inspired filigree ring with antique gold finish.', 'Nhẫn filigree lấy cảm hứng cổ điển với hoàn thiện vàng cổ điển tinh xảo.', 3100000, 3700000, 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600', 'Nhẫn filigree cổ điển vàng antique', 'NHN-010', 18, true, false, false, false, 'Vàng vàng 14k', 3.5, ARRAY['nhẫn', 'filigree', 'cổ điển', 'vintage']),
    (gen_random_uuid(), cat_nhan, 'Moonstone Silver Ring', 'Nhẫn Bạc Đá Mặt Trăng', 'nhan-bac-da-mat-trang', 'Mystical moonstone ring in sterling silver with a glowing adularescence effect.', 'Nhẫn đá mặt trăng huyền bí bằng bạc sterling với hiệu ứng phát sáng adularescence.', 2200000, 2600000, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600', 'Nhẫn bạc đá mặt trăng huyền bí', 'NHN-011', 25, true, true, false, false, 'Bạc 925, Đá mặt trăng', 2.9, ARRAY['nhẫn', 'đá mặt trăng', 'bạc', 'huyền bí']),
    (gen_random_uuid(), cat_nhan, 'Three Stone Diamond Ring', 'Nhẫn Ba Viên Kim Cương', 'nhan-ba-vien-kim-cuong', 'Symbolic three-stone diamond ring representing past, present, and future.', 'Nhẫn ba viên kim cương mang ý nghĩa tượng trưng cho quá khứ, hiện tại và tương lai.', 18500000, 21000000, 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600', 'Nhẫn ba viên kim cương vàng trắng', 'NHN-012', 7, true, false, true, true, 'Vàng trắng 18k, Kim cương', 4.8, ARRAY['nhẫn', 'kim cương', 'ba viên', 'đính hôn']),
    (gen_random_uuid(), cat_nhan, 'Opal Boho Ring', 'Nhẫn Boho Đá Opal', 'nhan-boho-da-opal', 'Free-spirited boho ring featuring a fire opal with rainbow color play.', 'Nhẫn boho phóng khoáng với đá opal lửa có sắc cầu vồng lung linh.', 2750000, 3200000, 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=600', 'Nhẫn boho đá opal lửa cầu vồng', 'NHN-013', 22, true, true, false, false, 'Bạc 925, Đá opal', 2.6, ARRAY['nhẫn', 'opal', 'boho', 'cầu vồng']),
    (gen_random_uuid(), cat_nhan, 'Eternity Band', 'Nhẫn Eternity', 'nhan-eternity', 'Dazzling eternity band with diamonds set all the way around the band.', 'Nhẫn eternity lấp lánh với kim cương được đính xung quanh toàn bộ vòng nhẫn.', 8900000, 10500000, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600', 'Nhẫn eternity kim cương toàn vòng', 'NHN-014', 14, true, false, true, false, 'Vàng trắng 18k, Kim cương', 3.9, ARRAY['nhẫn', 'eternity', 'kim cương', 'vàng trắng']),
    (gen_random_uuid(), cat_nhan, 'Amethyst Statement Ring', 'Nhẫn Đá Amethyst Nổi Bật', 'nhan-da-amethyst-noi-bat', 'Bold statement ring with a large oval amethyst in a gold prong setting.', 'Nhẫn nổi bật với đá amethyst hình bầu dục lớn trong khung vàng chấu.', 3400000, 3900000, 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600', 'Nhẫn đá amethyst tím lớn nổi bật', 'NHN-015', 28, true, false, false, false, 'Vàng vàng 14k, Amethyst', 4.2, ARRAY['nhẫn', 'amethyst', 'tím', 'nổi bật']),
    (gen_random_uuid(), cat_nhan, 'Minimalist Thin Band', 'Nhẫn Mỏng Tối Giản', 'nhan-mong-toi-gian', 'Ultra-thin minimalist band ring, perfect for stacking or wearing alone.', 'Nhẫn mỏng tối giản, hoàn hảo để xếp chồng hoặc đeo riêng lẻ.', 980000, NULL, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=600', 'Nhẫn mỏng tối giản bạc', 'NHN-016', 80, true, false, true, false, 'Bạc 925', 1.2, ARRAY['nhẫn', 'mỏng', 'tối giản', 'xếp chồng']),
    (gen_random_uuid(), cat_nhan, 'Aquamarine Oval Ring', 'Nhẫn Đá Aquamarine Bầu Dục', 'nhan-da-aquamarine-bau-duc', 'Serene aquamarine oval ring evoking the calm of the ocean in blue-green hues.', 'Nhẫn đá aquamarine hình bầu dục gợi lên sự bình yên của đại dương với sắc xanh lam.', 5600000, 6500000, 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600', 'Nhẫn đá aquamarine xanh biển bầu dục', 'NHN-017', 16, true, true, false, false, 'Vàng trắng 14k, Aquamarine', 3.7, ARRAY['nhẫn', 'aquamarine', 'xanh biển', 'bầu dục']),
    (gen_random_uuid(), cat_nhan, 'Citrine Gold Ring', 'Nhẫn Vàng Đá Citrine', 'nhan-vang-da-citrine', 'Warm and sunny citrine ring in yellow gold, radiating positive energy.', 'Nhẫn đá citrine ấm áp và tươi sáng trong vàng vàng, tỏa ra năng lượng tích cực.', 4100000, 4800000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Nhẫn vàng đá citrine vàng cam', 'NHN-018', 20, true, false, false, false, 'Vàng vàng 14k, Citrine', 3.4, ARRAY['nhẫn', 'citrine', 'vàng', 'năng lượng']),
    (gen_random_uuid(), cat_nhan, 'Floral Diamond Ring', 'Nhẫn Kim Cương Hoa', 'nhan-kim-cuong-hoa', 'Whimsical floral ring with diamond petals blooming in white gold.', 'Nhẫn hoa mộng mơ với cánh hoa kim cương nở rộ trong vàng trắng.', 11200000, 13000000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600', 'Nhẫn kim cương hình hoa vàng trắng', 'NHN-019', 9, true, true, true, false, 'Vàng trắng 18k, Kim cương', 4.0, ARRAY['nhẫn', 'kim cương', 'hoa', 'vàng trắng']),
    (gen_random_uuid(), cat_nhan, 'Black Diamond Ring', 'Nhẫn Kim Cương Đen', 'nhan-kim-cuong-den', 'Edgy and modern black diamond ring set in black rhodium plated silver.', 'Nhẫn kim cương đen cá tính và hiện đại được đặt trong bạc mạ rhodium đen.', 6800000, 7900000, 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600', 'Nhẫn kim cương đen rhodium đen', 'NHN-020', 13, true, true, false, false, 'Bạc 925 mạ rhodium đen, Kim cương đen', 3.6, ARRAY['nhẫn', 'kim cương đen', 'rhodium', 'cá tính'])
    ON CONFLICT (slug) DO NOTHING;

    -- =====================
    -- VÒNG TAY (Bracelets) - 20 products
    -- =====================
    INSERT INTO public.products (id, category_id, name, name_vi, slug, description, description_vi, price, original_price, image_url, image_alt, sku, stock_quantity, is_active, is_new, is_best_seller, is_featured, material, weight_grams, tags)
    VALUES
    (gen_random_uuid(), cat_vong, 'Tennis Bracelet', 'Vòng Tay Tennis Kim Cương', 'vong-tay-tennis-kim-cuong', 'Classic diamond tennis bracelet with a continuous line of brilliant-cut diamonds.', 'Vòng tay tennis kim cương cổ điển với hàng kim cương cắt brilliant liên tục.', 28500000, 33000000, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', 'Vòng tay tennis kim cương cổ điển', 'VTT-001', 6, true, false, true, true, 'Vàng trắng 18k, Kim cương', 8.5, ARRAY['vòng tay', 'tennis', 'kim cương', 'cổ điển']),
    (gen_random_uuid(), cat_vong, 'Gold Bangle Bracelet', 'Vòng Tay Bangle Vàng', 'vong-tay-bangle-vang', 'Sleek solid gold bangle bracelet with a polished finish for everyday elegance.', 'Vòng tay bangle vàng đặc bóng với hoàn thiện đánh bóng cho sự thanh lịch hàng ngày.', 7800000, 9000000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Vòng tay bangle vàng đặc bóng', 'VTT-002', 25, true, false, true, false, 'Vàng vàng 18k', 12.0, ARRAY['vòng tay', 'bangle', 'vàng', 'thanh lịch']),
    (gen_random_uuid(), cat_vong, 'Pearl Strand Bracelet', 'Vòng Tay Chuỗi Ngọc Trai', 'vong-tay-chuoi-ngoc-trai', 'Elegant freshwater pearl strand bracelet with a gold lobster clasp.', 'Vòng tay chuỗi ngọc trai nước ngọt thanh lịch với khóa tôm vàng.', 4500000, 5200000, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600', 'Vòng tay chuỗi ngọc trai nước ngọt', 'VTT-003', 20, true, true, false, false, 'Ngọc trai, Vàng 14k', 6.2, ARRAY['vòng tay', 'ngọc trai', 'chuỗi', 'thanh lịch']),
    (gen_random_uuid(), cat_vong, 'Charm Bracelet', 'Vòng Tay Charm', 'vong-tay-charm', 'Playful charm bracelet with a mix of gold and silver charms for personalization.', 'Vòng tay charm vui nhộn với hỗn hợp charm vàng và bạc để cá nhân hóa.', 3200000, 3800000, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600', 'Vòng tay charm vàng bạc cá nhân hóa', 'VTT-004', 35, true, true, true, false, 'Bạc 925, Vàng 14k', 5.8, ARRAY['vòng tay', 'charm', 'cá nhân hóa', 'vui nhộn']),
    (gen_random_uuid(), cat_vong, 'Cuff Bracelet', 'Vòng Tay Cuff Bạc', 'vong-tay-cuff-bac', 'Bold open cuff bracelet in sterling silver with hammered texture.', 'Vòng tay cuff mở mạnh mẽ bằng bạc sterling với kết cấu búa.', 2100000, 2500000, 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600', 'Vòng tay cuff bạc kết cấu búa', 'VTT-005', 30, true, false, false, false, 'Bạc 925', 9.5, ARRAY['vòng tay', 'cuff', 'bạc', 'búa']),
    (gen_random_uuid(), cat_vong, 'Rose Gold Chain Bracelet', 'Vòng Tay Dây Chuyền Vàng Hồng', 'vong-tay-day-chuyen-vang-hong', 'Delicate rose gold chain bracelet with a heart-shaped lobster clasp.', 'Vòng tay dây chuyền vàng hồng tinh tế với khóa tôm hình trái tim.', 1850000, 2200000, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600', 'Vòng tay dây chuyền vàng hồng tinh tế', 'VTT-006', 45, true, true, false, false, 'Vàng hồng 14k', 3.1, ARRAY['vòng tay', 'dây chuyền', 'vàng hồng', 'tinh tế']),
    (gen_random_uuid(), cat_vong, 'Sapphire Link Bracelet', 'Vòng Tay Mắt Xích Sapphire', 'vong-tay-mat-xich-sapphire', 'Luxurious link bracelet alternating sapphires and diamonds in white gold.', 'Vòng tay mắt xích sang trọng xen kẽ sapphire và kim cương trong vàng trắng.', 16500000, 19000000, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600', 'Vòng tay mắt xích sapphire kim cương vàng trắng', 'VTT-007', 8, true, false, true, true, 'Vàng trắng 18k, Sapphire, Kim cương', 10.2, ARRAY['vòng tay', 'sapphire', 'kim cương', 'mắt xích']),
    (gen_random_uuid(), cat_vong, 'Beaded Gemstone Bracelet', 'Vòng Tay Đá Quý Hạt', 'vong-tay-da-quy-hat', 'Colorful beaded bracelet featuring natural gemstones for healing energy.', 'Vòng tay hạt đá quý tự nhiên đầy màu sắc mang năng lượng chữa lành.', 1200000, 1500000, 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=600', 'Vòng tay hạt đá quý tự nhiên màu sắc', 'VTT-008', 55, true, false, false, false, 'Đá quý tự nhiên', 7.3, ARRAY['vòng tay', 'đá quý', 'hạt', 'năng lượng']),
    (gen_random_uuid(), cat_vong, 'Diamond Pave Bracelet', 'Vòng Tay Pave Kim Cương', 'vong-tay-pave-kim-cuong', 'Glamorous pave diamond bracelet with hundreds of tiny diamonds set closely together.', 'Vòng tay pave kim cương lộng lẫy với hàng trăm viên kim cương nhỏ được đặt sát nhau.', 35000000, 40000000, 'https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=600', 'Vòng tay pave kim cương lộng lẫy', 'VTT-009', 4, true, false, true, true, 'Vàng trắng 18k, Kim cương', 9.8, ARRAY['vòng tay', 'pave', 'kim cương', 'lộng lẫy']),
    (gen_random_uuid(), cat_vong, 'Leather Wrap Bracelet', 'Vòng Tay Da Quấn', 'vong-tay-da-quan', 'Bohemian leather wrap bracelet with gold accents and turquoise stones.', 'Vòng tay da quấn phong cách bohemian với điểm nhấn vàng và đá turquoise.', 850000, 1100000, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600', 'Vòng tay da quấn bohemian vàng turquoise', 'VTT-010', 40, true, true, false, false, 'Da, Vàng 14k, Turquoise', 4.5, ARRAY['vòng tay', 'da', 'quấn', 'bohemian']),
    (gen_random_uuid(), cat_vong, 'Infinity Bracelet', 'Vòng Tay Vô Cực', 'vong-tay-vo-cuc', 'Meaningful infinity symbol bracelet in sterling silver with cubic zirconia.', 'Vòng tay biểu tượng vô cực ý nghĩa bằng bạc sterling với đá cubic zirconia.', 1450000, 1750000, 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600', 'Vòng tay vô cực bạc cubic zirconia', 'VTT-011', 50, true, true, true, false, 'Bạc 925, Cubic Zirconia', 4.0, ARRAY['vòng tay', 'vô cực', 'bạc', 'ý nghĩa']),
    (gen_random_uuid(), cat_vong, 'Emerald Gold Bracelet', 'Vòng Tay Vàng Đá Emerald', 'vong-tay-vang-da-emerald', 'Regal emerald and gold bracelet fit for royalty with deep green stones.', 'Vòng tay emerald và vàng sang trọng xứng đáng với hoàng gia với đá xanh lá đậm.', 14200000, 16500000, 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600', 'Vòng tay vàng đá emerald xanh lá đậm', 'VTT-012', 7, true, false, false, true, 'Vàng vàng 18k, Emerald', 11.5, ARRAY['vòng tay', 'emerald', 'vàng', 'sang trọng']),
    (gen_random_uuid(), cat_vong, 'Adjustable Friendship Bracelet', 'Vòng Tay Tình Bạn Điều Chỉnh', 'vong-tay-tinh-ban-dieu-chinh', 'Sweet adjustable friendship bracelet with engraved message in gold.', 'Vòng tay tình bạn điều chỉnh ngọt ngào với thông điệp khắc bằng vàng.', 780000, 950000, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=600', 'Vòng tay tình bạn điều chỉnh khắc chữ vàng', 'VTT-013', 70, true, true, false, false, 'Bạc 925 mạ vàng', 2.5, ARRAY['vòng tay', 'tình bạn', 'điều chỉnh', 'quà tặng']),
    (gen_random_uuid(), cat_vong, 'Turquoise Bangle', 'Vòng Tay Bangle Turquoise', 'vong-tay-bangle-turquoise', 'Vibrant turquoise bangle bracelet with silver tribal patterns.', 'Vòng tay bangle turquoise sống động với hoa văn bộ lạc bạc.', 1680000, 2000000, 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600', 'Vòng tay bangle turquoise hoa văn bộ lạc', 'VTT-014', 28, true, false, false, false, 'Bạc 925, Turquoise', 8.0, ARRAY['vòng tay', 'turquoise', 'bangle', 'bộ lạc']),
    (gen_random_uuid(), cat_vong, 'Gold Snake Chain Bracelet', 'Vòng Tay Dây Rắn Vàng', 'vong-tay-day-ran-vang', 'Sleek snake chain bracelet in 18k gold with a smooth, flexible design.', 'Vòng tay dây rắn bóng trong vàng 18k với thiết kế mượt mà và linh hoạt.', 5200000, 6100000, 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600', 'Vòng tay dây rắn vàng 18k mượt mà', 'VTT-015', 22, true, false, true, false, 'Vàng vàng 18k', 6.8, ARRAY['vòng tay', 'dây rắn', 'vàng', 'linh hoạt']),
    (gen_random_uuid(), cat_vong, 'Crystal Beaded Bracelet', 'Vòng Tay Hạt Pha Lê', 'vong-tay-hat-pha-le', 'Sparkling crystal beaded bracelet in a rainbow of colors for a festive look.', 'Vòng tay hạt pha lê lấp lánh với nhiều màu sắc cầu vồng cho vẻ ngoài lễ hội.', 650000, 850000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Vòng tay hạt pha lê cầu vồng lễ hội', 'VTT-016', 65, true, true, false, false, 'Pha lê Swarovski', 5.2, ARRAY['vòng tay', 'pha lê', 'hạt', 'cầu vồng']),
    (gen_random_uuid(), cat_vong, 'Amethyst Cluster Bracelet', 'Vòng Tay Chùm Amethyst', 'vong-tay-chum-amethyst', 'Stunning amethyst cluster bracelet with raw purple crystals in gold setting.', 'Vòng tay chùm amethyst ấn tượng với tinh thể tím thô trong khung vàng.', 3900000, 4600000, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', 'Vòng tay chùm amethyst tím thô vàng', 'VTT-017', 18, true, false, false, false, 'Vàng 14k, Amethyst', 7.6, ARRAY['vòng tay', 'amethyst', 'chùm', 'tím']),
    (gen_random_uuid(), cat_vong, 'Platinum Diamond Bracelet', 'Vòng Tay Kim Cương Bạch Kim', 'vong-tay-kim-cuong-bach-kim', 'Exquisite platinum bracelet with channel-set diamonds for ultimate luxury.', 'Vòng tay bạch kim tinh xảo với kim cương đặt kênh cho sự sang trọng tối thượng.', 42000000, 48000000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600', 'Vòng tay bạch kim kim cương đặt kênh', 'VTT-018', 3, true, false, true, true, 'Bạch kim, Kim cương', 14.0, ARRAY['vòng tay', 'bạch kim', 'kim cương', 'sang trọng']),
    (gen_random_uuid(), cat_vong, 'Floral Enamel Bracelet', 'Vòng Tay Men Hoa', 'vong-tay-men-hoa', 'Colorful floral enamel bracelet with hand-painted flower motifs in gold.', 'Vòng tay men hoa đầy màu sắc với họa tiết hoa được vẽ tay trong vàng.', 2300000, 2800000, 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600', 'Vòng tay men hoa vẽ tay vàng', 'VTT-019', 32, true, true, false, false, 'Vàng 14k, Men', 6.5, ARRAY['vòng tay', 'men', 'hoa', 'vẽ tay']),
    (gen_random_uuid(), cat_vong, 'Vintage Pearl Bracelet', 'Vòng Tay Ngọc Trai Cổ Điển', 'vong-tay-ngoc-trai-co-dien', 'Timeless vintage-style pearl bracelet with a diamond-studded gold clasp.', 'Vòng tay ngọc trai phong cách cổ điển vượt thời gian với khóa vàng đính kim cương.', 6200000, 7200000, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600', 'Vòng tay ngọc trai cổ điển khóa vàng kim cương', 'VTT-020', 12, true, false, true, false, 'Ngọc trai, Vàng 18k, Kim cương', 8.9, ARRAY['vòng tay', 'ngọc trai', 'cổ điển', 'vintage'])
    ON CONFLICT (slug) DO NOTHING;

    -- =====================
    -- DÂY CHUYỀN (Necklaces) - 20 products
    -- =====================
    INSERT INTO public.products (id, category_id, name, name_vi, slug, description, description_vi, price, original_price, image_url, image_alt, sku, stock_quantity, is_active, is_new, is_best_seller, is_featured, material, weight_grams, tags)
    VALUES
    (gen_random_uuid(), cat_day, 'Diamond Pendant Necklace', 'Dây Chuyền Mặt Kim Cương', 'day-chuyen-mat-kim-cuong', 'Brilliant diamond pendant necklace on a delicate 18k white gold chain.', 'Dây chuyền mặt kim cương lấp lánh trên dây chuyền vàng trắng 18k tinh tế.', 12500000, 14500000, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600', 'Dây chuyền mặt kim cương vàng trắng 18k', 'DCH-001', 15, true, false, true, true, 'Vàng trắng 18k, Kim cương', 4.2, ARRAY['dây chuyền', 'kim cương', 'mặt', 'vàng trắng']),
    (gen_random_uuid(), cat_day, 'Gold Heart Necklace', 'Dây Chuyền Trái Tim Vàng', 'day-chuyen-trai-tim-vang', 'Romantic gold heart necklace, a perfect gift for someone special.', 'Dây chuyền trái tim vàng lãng mạn, món quà hoàn hảo cho người đặc biệt.', 3800000, 4500000, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600', 'Dây chuyền trái tim vàng lãng mạn', 'DCH-002', 30, true, true, true, false, 'Vàng vàng 14k', 3.5, ARRAY['dây chuyền', 'trái tim', 'vàng', 'quà tặng']),
    (gen_random_uuid(), cat_day, 'Pearl Choker Necklace', 'Dây Chuyền Choker Ngọc Trai', 'day-chuyen-choker-ngoc-trai', 'Classic pearl choker necklace with a single strand of lustrous pearls.', 'Dây chuyền choker ngọc trai cổ điển với một sợi ngọc trai óng ánh.', 5500000, 6400000, 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600', 'Dây chuyền choker ngọc trai cổ điển', 'DCH-003', 18, true, false, true, false, 'Ngọc trai, Vàng 14k', 12.0, ARRAY['dây chuyền', 'choker', 'ngọc trai', 'cổ điển']),
    (gen_random_uuid(), cat_day, 'Layered Gold Necklace', 'Dây Chuyền Vàng Nhiều Lớp', 'day-chuyen-vang-nhieu-lop', 'Trendy layered gold necklace set with three chains of varying lengths.', 'Bộ dây chuyền vàng nhiều lớp thời trang với ba sợi dây có độ dài khác nhau.', 4200000, 5000000, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600', 'Dây chuyền vàng nhiều lớp thời trang', 'DCH-004', 25, true, true, false, false, 'Vàng vàng 14k', 5.8, ARRAY['dây chuyền', 'nhiều lớp', 'vàng', 'thời trang']),
    (gen_random_uuid(), cat_day, 'Sapphire Drop Necklace', 'Dây Chuyền Mặt Sapphire Thả', 'day-chuyen-mat-sapphire-tha', 'Elegant sapphire drop necklace with a pear-shaped blue sapphire in gold.', 'Dây chuyền mặt sapphire thả thanh lịch với đá sapphire xanh hình lê trong vàng.', 9800000, 11500000, 'https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=600', 'Dây chuyền mặt sapphire xanh hình lê vàng', 'DCH-005', 10, true, false, false, true, 'Vàng vàng 18k, Sapphire', 5.1, ARRAY['dây chuyền', 'sapphire', 'thả', 'xanh']),
    (gen_random_uuid(), cat_day, 'Silver Cross Necklace', 'Dây Chuyền Thánh Giá Bạc', 'day-chuyen-thanh-gia-bac', 'Meaningful silver cross necklace with intricate engraving and diamond accent.', 'Dây chuyền thánh giá bạc ý nghĩa với khắc tinh xảo và điểm nhấn kim cương.', 2100000, 2500000, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600', 'Dây chuyền thánh giá bạc khắc tinh xảo', 'DCH-006', 35, true, false, false, false, 'Bạc 925, Kim cương', 4.8, ARRAY['dây chuyền', 'thánh giá', 'bạc', 'ý nghĩa']),
    (gen_random_uuid(), cat_day, 'Emerald Pendant Necklace', 'Dây Chuyền Mặt Emerald', 'day-chuyen-mat-emerald', 'Luxurious emerald pendant necklace with a vivid green emerald in white gold.', 'Dây chuyền mặt emerald sang trọng với đá emerald xanh lá rực rỡ trong vàng trắng.', 18000000, 21000000, 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600', 'Dây chuyền mặt emerald xanh lá vàng trắng', 'DCH-007', 6, true, false, true, true, 'Vàng trắng 18k, Emerald', 5.6, ARRAY['dây chuyền', 'emerald', 'xanh lá', 'sang trọng']),
    (gen_random_uuid(), cat_day, 'Butterfly Necklace', 'Dây Chuyền Bướm', 'day-chuyen-buom', 'Whimsical butterfly necklace with colorful enamel wings in rose gold.', 'Dây chuyền bướm mộng mơ với cánh men màu sắc trong vàng hồng.', 2650000, 3100000, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=600', 'Dây chuyền bướm men màu vàng hồng', 'DCH-008', 28, true, true, false, false, 'Vàng hồng 14k, Men', 3.9, ARRAY['dây chuyền', 'bướm', 'men', 'vàng hồng']),
    (gen_random_uuid(), cat_day, 'Ruby Heart Necklace', 'Dây Chuyền Trái Tim Ruby', 'day-chuyen-trai-tim-ruby', 'Passionate ruby heart necklace with a deep red ruby in yellow gold.', 'Dây chuyền trái tim ruby đam mê với đá ruby đỏ đậm trong vàng vàng.', 7500000, 8800000, 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600', 'Dây chuyền trái tim ruby đỏ vàng vàng', 'DCH-009', 12, true, false, true, false, 'Vàng vàng 18k, Ruby', 4.7, ARRAY['dây chuyền', 'ruby', 'trái tim', 'đỏ']),
    (gen_random_uuid(), cat_day, 'Minimalist Bar Necklace', 'Dây Chuyền Thanh Tối Giản', 'day-chuyen-thanh-toi-gian', 'Sleek minimalist bar necklace with optional engraving in sterling silver.', 'Dây chuyền thanh tối giản bóng với tùy chọn khắc chữ bằng bạc sterling.', 1350000, 1650000, 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600', 'Dây chuyền thanh tối giản bạc khắc chữ', 'DCH-010', 55, true, true, false, false, 'Bạc 925', 3.2, ARRAY['dây chuyền', 'thanh', 'tối giản', 'khắc chữ']),
    (gen_random_uuid(), cat_day, 'Opal Teardrop Necklace', 'Dây Chuyền Giọt Nước Opal', 'day-chuyen-giot-nuoc-opal', 'Dreamy opal teardrop necklace with a shimmering fire opal in silver.', 'Dây chuyền giọt nước opal mơ mộng với đá opal lửa lấp lánh trong bạc.', 3100000, 3700000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Dây chuyền giọt nước opal lửa bạc', 'DCH-011', 20, true, true, false, false, 'Bạc 925, Opal', 3.8, ARRAY['dây chuyền', 'opal', 'giọt nước', 'lửa']),
    (gen_random_uuid(), cat_day, 'Gold Chain Necklace', 'Dây Chuyền Vàng Trơn', 'day-chuyen-vang-tron', 'Classic Cuban link gold chain necklace, a wardrobe staple for any occasion.', 'Dây chuyền vàng Cuban link cổ điển, phụ kiện tủ quần áo cho mọi dịp.', 8500000, NULL, 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600', 'Dây chuyền vàng Cuban link cổ điển', 'DCH-012', 20, true, false, true, false, 'Vàng vàng 18k', 15.0, ARRAY['dây chuyền', 'vàng', 'Cuban link', 'cổ điển']),
    (gen_random_uuid(), cat_day, 'Moonstone Pendant', 'Mặt Dây Chuyền Đá Mặt Trăng', 'mat-day-chuyen-da-mat-trang', 'Ethereal moonstone pendant necklace with a glowing blue moonstone in silver.', 'Dây chuyền mặt đá mặt trăng huyền ảo với đá mặt trăng xanh phát sáng trong bạc.', 2450000, 2900000, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', 'Mặt dây chuyền đá mặt trăng xanh bạc', 'DCH-013', 22, true, true, false, false, 'Bạc 925, Đá mặt trăng', 4.1, ARRAY['dây chuyền', 'đá mặt trăng', 'mặt', 'huyền ảo']),
    (gen_random_uuid(), cat_day, 'Aquamarine Necklace', 'Dây Chuyền Đá Aquamarine', 'day-chuyen-da-aquamarine', 'Ocean-inspired aquamarine necklace with a faceted blue-green stone in gold.', 'Dây chuyền đá aquamarine lấy cảm hứng từ đại dương với đá xanh lam được cắt mài trong vàng.', 6800000, 7900000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600', 'Dây chuyền đá aquamarine xanh biển vàng', 'DCH-014', 14, true, false, false, false, 'Vàng vàng 14k, Aquamarine', 4.9, ARRAY['dây chuyền', 'aquamarine', 'xanh biển', 'đại dương']),
    (gen_random_uuid(), cat_day, 'Vintage Locket Necklace', 'Dây Chuyền Hộp Ảnh Cổ Điển', 'day-chuyen-hop-anh-co-dien', 'Sentimental vintage locket necklace with engraved floral pattern in gold.', 'Dây chuyền hộp ảnh cổ điển đầy cảm xúc với hoa văn hoa khắc trong vàng.', 3500000, 4100000, 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600', 'Dây chuyền hộp ảnh cổ điển hoa văn vàng', 'DCH-015', 18, true, false, false, false, 'Vàng vàng 14k', 6.3, ARRAY['dây chuyền', 'hộp ảnh', 'cổ điển', 'kỷ niệm']),
    (gen_random_uuid(), cat_day, 'Star Constellation Necklace', 'Dây Chuyền Chòm Sao', 'day-chuyen-chom-sao', 'Celestial star constellation necklace with diamond stars on a gold chain.', 'Dây chuyền chòm sao thiên thể với ngôi sao kim cương trên dây chuyền vàng.', 4800000, 5600000, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600', 'Dây chuyền chòm sao kim cương vàng', 'DCH-016', 16, true, true, false, false, 'Vàng vàng 14k, Kim cương', 3.7, ARRAY['dây chuyền', 'chòm sao', 'kim cương', 'thiên thể']),
    (gen_random_uuid(), cat_day, 'Amethyst Cluster Necklace', 'Dây Chuyền Chùm Amethyst', 'day-chuyen-chum-amethyst', 'Bohemian amethyst cluster necklace with raw purple crystals on a gold chain.', 'Dây chuyền chùm amethyst phong cách bohemian với tinh thể tím thô trên dây vàng.', 3200000, 3800000, 'https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=600', 'Dây chuyền chùm amethyst tím thô vàng', 'DCH-017', 24, true, false, false, false, 'Vàng 14k, Amethyst', 5.5, ARRAY['dây chuyền', 'amethyst', 'chùm', 'bohemian']),
    (gen_random_uuid(), cat_day, 'Diamond Infinity Necklace', 'Dây Chuyền Vô Cực Kim Cương', 'day-chuyen-vo-cuc-kim-cuong', 'Symbolic diamond infinity necklace representing endless love in white gold.', 'Dây chuyền vô cực kim cương mang ý nghĩa tình yêu vô tận trong vàng trắng.', 8200000, 9600000, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600', 'Dây chuyền vô cực kim cương vàng trắng', 'DCH-018', 11, true, true, true, false, 'Vàng trắng 18k, Kim cương', 4.4, ARRAY['dây chuyền', 'vô cực', 'kim cương', 'tình yêu']),
    (gen_random_uuid(), cat_day, 'Citrine Sun Necklace', 'Dây Chuyền Mặt Trời Citrine', 'day-chuyen-mat-troi-citrine', 'Radiant sun-shaped citrine necklace bringing warmth and positivity.', 'Dây chuyền hình mặt trời citrine rực rỡ mang lại sự ấm áp và tích cực.', 2900000, 3400000, 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600', 'Dây chuyền mặt trời citrine vàng cam', 'DCH-019', 26, true, true, false, false, 'Vàng 14k, Citrine', 4.0, ARRAY['dây chuyền', 'citrine', 'mặt trời', 'tích cực']),
    (gen_random_uuid(), cat_day, 'Platinum Diamond Solitaire Necklace', 'Dây Chuyền Bạch Kim Kim Cương Solitaire', 'day-chuyen-bach-kim-kim-cuong-solitaire', 'Ultimate luxury platinum necklace with a single brilliant-cut diamond solitaire.', 'Dây chuyền bạch kim sang trọng tối thượng với một viên kim cương solitaire cắt brilliant.', 32000000, 37000000, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=600', 'Dây chuyền bạch kim kim cương solitaire sang trọng', 'DCH-020', 4, true, false, true, true, 'Bạch kim, Kim cương', 5.8, ARRAY['dây chuyền', 'bạch kim', 'kim cương', 'solitaire'])
    ON CONFLICT (slug) DO NOTHING;

    -- =====================
    -- BÔNG TAI (Earrings) - 20 products
    -- =====================
    INSERT INTO public.products (id, category_id, name, name_vi, slug, description, description_vi, price, original_price, image_url, image_alt, sku, stock_quantity, is_active, is_new, is_best_seller, is_featured, material, weight_grams, tags)
    VALUES
    (gen_random_uuid(), cat_bong, 'Diamond Stud Earrings', 'Bông Tai Kim Cương Nụ', 'bong-tai-kim-cuong-nu', 'Classic diamond stud earrings, a timeless jewelry staple in white gold.', 'Bông tai kim cương nụ cổ điển, phụ kiện trang sức vượt thời gian trong vàng trắng.', 9500000, 11000000, 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600', 'Bông tai kim cương nụ vàng trắng cổ điển', 'BTE-001', 20, true, false, true, true, 'Vàng trắng 18k, Kim cương', 2.8, ARRAY['bông tai', 'kim cương', 'nụ', 'cổ điển']),
    (gen_random_uuid(), cat_bong, 'Pearl Drop Earrings', 'Bông Tai Ngọc Trai Thả', 'bong-tai-ngoc-trai-tha', 'Elegant freshwater pearl drop earrings with gold hooks for a sophisticated look.', 'Bông tai ngọc trai nước ngọt thả thanh lịch với móc vàng cho vẻ ngoài tinh tế.', 3800000, 4500000, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600', 'Bông tai ngọc trai thả vàng tinh tế', 'BTE-002', 25, true, true, false, false, 'Ngọc trai, Vàng 14k', 3.5, ARRAY['bông tai', 'ngọc trai', 'thả', 'tinh tế']),
    (gen_random_uuid(), cat_bong, 'Gold Hoop Earrings', 'Bông Tai Khuyên Vàng', 'bong-tai-khuyen-vang', 'Versatile gold hoop earrings in a medium size, perfect for any occasion.', 'Bông tai khuyên vàng linh hoạt cỡ vừa, hoàn hảo cho mọi dịp.', 4200000, 5000000, 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600', 'Bông tai khuyên vàng cỡ vừa linh hoạt', 'BTE-003', 35, true, false, true, false, 'Vàng vàng 18k', 4.1, ARRAY['bông tai', 'khuyên', 'vàng', 'linh hoạt']),
    (gen_random_uuid(), cat_bong, 'Sapphire Chandelier Earrings', 'Bông Tai Chùm Sapphire', 'bong-tai-chum-sapphire', 'Dramatic sapphire chandelier earrings with cascading blue sapphires in gold.', 'Bông tai chùm sapphire ấn tượng với sapphire xanh tầng tầng trong vàng.', 14500000, 17000000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Bông tai chùm sapphire xanh tầng vàng', 'BTE-004', 8, true, false, true, true, 'Vàng vàng 18k, Sapphire', 6.2, ARRAY['bông tai', 'sapphire', 'chùm', 'ấn tượng']),
    (gen_random_uuid(), cat_bong, 'Rose Gold Flower Earrings', 'Bông Tai Hoa Vàng Hồng', 'bong-tai-hoa-vang-hong', 'Delicate rose gold flower earrings with diamond center stones.', 'Bông tai hoa vàng hồng tinh tế với đá kim cương ở trung tâm.', 5600000, 6500000, 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600', 'Bông tai hoa vàng hồng kim cương trung tâm', 'BTE-005', 18, true, true, false, false, 'Vàng hồng 14k, Kim cương', 3.8, ARRAY['bông tai', 'hoa', 'vàng hồng', 'kim cương']),
    (gen_random_uuid(), cat_bong, 'Emerald Stud Earrings', 'Bông Tai Nụ Emerald', 'bong-tai-nu-emerald', 'Vivid emerald stud earrings with deep green stones in yellow gold bezels.', 'Bông tai nụ emerald rực rỡ với đá xanh lá đậm trong viền vàng vàng.', 7800000, 9100000, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', 'Bông tai nụ emerald xanh lá vàng vàng', 'BTE-006', 12, true, false, false, false, 'Vàng vàng 18k, Emerald', 2.9, ARRAY['bông tai', 'emerald', 'nụ', 'xanh lá']),
    (gen_random_uuid(), cat_bong, 'Crystal Tassel Earrings', 'Bông Tai Tua Pha Lê', 'bong-tai-tua-pha-le', 'Glamorous crystal tassel earrings with cascading Swarovski crystals.', 'Bông tai tua pha lê lộng lẫy với pha lê Swarovski tầng tầng.', 2200000, 2700000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600', 'Bông tai tua pha lê Swarovski lộng lẫy', 'BTE-007', 30, true, true, false, false, 'Bạc 925, Pha lê Swarovski', 5.5, ARRAY['bông tai', 'tua', 'pha lê', 'lộng lẫy']),
    (gen_random_uuid(), cat_bong, 'Ruby Cluster Earrings', 'Bông Tai Chùm Ruby', 'bong-tai-chum-ruby', 'Passionate ruby cluster earrings with deep red rubies surrounded by diamonds.', 'Bông tai chùm ruby đam mê với ruby đỏ đậm được bao quanh bởi kim cương.', 11500000, 13500000, 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600', 'Bông tai chùm ruby đỏ kim cương', 'BTE-008', 9, true, false, true, false, 'Vàng vàng 18k, Ruby, Kim cương', 4.6, ARRAY['bông tai', 'ruby', 'chùm', 'kim cương']),
    (gen_random_uuid(), cat_bong, 'Silver Geometric Earrings', 'Bông Tai Hình Học Bạc', 'bong-tai-hinh-hoc-bac', 'Modern geometric earrings in sterling silver with angular design.', 'Bông tai hình học hiện đại bằng bạc sterling với thiết kế góc cạnh.', 1450000, 1750000, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600', 'Bông tai hình học bạc góc cạnh hiện đại', 'BTE-009', 40, true, true, false, false, 'Bạc 925', 3.2, ARRAY['bông tai', 'hình học', 'bạc', 'hiện đại']),
    (gen_random_uuid(), cat_bong, 'Moonstone Crescent Earrings', 'Bông Tai Trăng Lưỡi Liềm Đá Mặt Trăng', 'bong-tai-trang-luoi-liem-da-mat-trang', 'Mystical crescent moon earrings with glowing moonstones in silver.', 'Bông tai trăng lưỡi liềm huyền bí với đá mặt trăng phát sáng trong bạc.', 2800000, 3300000, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600', 'Bông tai trăng lưỡi liềm đá mặt trăng bạc', 'BTE-010', 22, true, true, false, false, 'Bạc 925, Đá mặt trăng', 3.9, ARRAY['bông tai', 'trăng lưỡi liềm', 'đá mặt trăng', 'huyền bí']),
    (gen_random_uuid(), cat_bong, 'Diamond Huggie Earrings', 'Bông Tai Huggie Kim Cương', 'bong-tai-huggie-kim-cuong', 'Chic diamond huggie earrings that hug the earlobe with pave diamonds.', 'Bông tai huggie kim cương sành điệu ôm sát dái tai với kim cương pave.', 7200000, 8400000, 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600', 'Bông tai huggie kim cương pave sành điệu', 'BTE-011', 16, true, false, true, false, 'Vàng vàng 18k, Kim cương', 3.4, ARRAY['bông tai', 'huggie', 'kim cương', 'pave']),
    (gen_random_uuid(), cat_bong, 'Turquoise Dangle Earrings', 'Bông Tai Thả Turquoise', 'bong-tai-tha-turquoise', 'Bohemian turquoise dangle earrings with silver feather accents.', 'Bông tai thả turquoise phong cách bohemian với điểm nhấn lông vũ bạc.', 1650000, 2000000, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600', 'Bông tai thả turquoise lông vũ bạc bohemian', 'BTE-012', 32, true, false, false, false, 'Bạc 925, Turquoise', 4.8, ARRAY['bông tai', 'turquoise', 'thả', 'bohemian']),
    (gen_random_uuid(), cat_bong, 'Gold Ear Cuff', 'Bông Tai Cuff Vàng', 'bong-tai-cuff-vang', 'Edgy gold ear cuff that wraps around the ear with no piercing needed.', 'Bông tai cuff vàng cá tính quấn quanh tai không cần xỏ lỗ.', 1900000, 2300000, 'https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=600', 'Bông tai cuff vàng không cần xỏ lỗ', 'BTE-013', 38, true, true, false, false, 'Vàng 14k', 2.1, ARRAY['bông tai', 'cuff', 'vàng', 'không xỏ lỗ']),
    (gen_random_uuid(), cat_bong, 'Amethyst Teardrop Earrings', 'Bông Tai Giọt Nước Amethyst', 'bong-tai-giot-nuoc-amethyst', 'Graceful amethyst teardrop earrings with faceted purple stones in gold.', 'Bông tai giọt nước amethyst duyên dáng với đá tím được cắt mài trong vàng.', 4100000, 4800000, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600', 'Bông tai giọt nước amethyst tím vàng', 'BTE-014', 20, true, false, false, false, 'Vàng 14k, Amethyst', 4.3, ARRAY['bông tai', 'amethyst', 'giọt nước', 'tím']),
    (gen_random_uuid(), cat_bong, 'Opal Stud Earrings', 'Bông Tai Nụ Opal', 'bong-tai-nu-opal', 'Magical opal stud earrings with rainbow fire opal stones in silver.', 'Bông tai nụ opal kỳ diệu với đá opal lửa cầu vồng trong bạc.', 2500000, 3000000, 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600', 'Bông tai nụ opal lửa cầu vồng bạc', 'BTE-015', 28, true, true, false, false, 'Bạc 925, Opal', 2.6, ARRAY['bông tai', 'opal', 'nụ', 'cầu vồng']),
    (gen_random_uuid(), cat_bong, 'Vintage Cameo Earrings', 'Bông Tai Cameo Cổ Điển', 'bong-tai-cameo-co-dien', 'Antique-inspired cameo earrings with hand-carved shell portraits in gold.', 'Bông tai cameo lấy cảm hứng cổ điển với chân dung vỏ sò điêu khắc tay trong vàng.', 3300000, 3900000, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=600', 'Bông tai cameo vỏ sò điêu khắc tay vàng', 'BTE-016', 15, true, false, false, false, 'Vàng 14k, Vỏ sò', 3.7, ARRAY['bông tai', 'cameo', 'cổ điển', 'điêu khắc']),
    (gen_random_uuid(), cat_bong, 'Diamond Pear Drop Earrings', 'Bông Tai Kim Cương Hình Lê', 'bong-tai-kim-cuong-hinh-le', 'Sophisticated pear-shaped diamond drop earrings in platinum for special occasions.', 'Bông tai kim cương hình lê tinh tế trong bạch kim cho những dịp đặc biệt.', 24000000, 28000000, 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600', 'Bông tai kim cương hình lê bạch kim đặc biệt', 'BTE-017', 5, true, false, true, true, 'Bạch kim, Kim cương', 5.1, ARRAY['bông tai', 'kim cương', 'hình lê', 'bạch kim']),
    (gen_random_uuid(), cat_bong, 'Citrine Sun Earrings', 'Bông Tai Mặt Trời Citrine', 'bong-tai-mat-troi-citrine', 'Cheerful sun-shaped citrine earrings radiating warmth in yellow gold.', 'Bông tai hình mặt trời citrine vui tươi tỏa sáng trong vàng vàng.', 3600000, 4200000, 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600', 'Bông tai mặt trời citrine vàng vàng vui tươi', 'BTE-018', 24, true, true, false, false, 'Vàng 14k, Citrine', 3.3, ARRAY['bông tai', 'citrine', 'mặt trời', 'vui tươi']),
    (gen_random_uuid(), cat_bong, 'Aquamarine Oval Earrings', 'Bông Tai Bầu Dục Aquamarine', 'bong-tai-bau-duc-aquamarine', 'Serene aquamarine oval earrings in white gold evoking the calm ocean.', 'Bông tai bầu dục aquamarine trong vàng trắng gợi lên sự bình yên của đại dương.', 5900000, 6900000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Bông tai bầu dục aquamarine xanh biển vàng trắng', 'BTE-019', 14, true, false, false, false, 'Vàng trắng 14k, Aquamarine', 3.6, ARRAY['bông tai', 'aquamarine', 'bầu dục', 'xanh biển']),
    (gen_random_uuid(), cat_bong, 'Black Pearl Earrings', 'Bông Tai Ngọc Trai Đen', 'bong-tai-ngoc-trai-den', 'Exotic black Tahitian pearl earrings with diamond accents in white gold.', 'Bông tai ngọc trai Tahiti đen kỳ lạ với điểm nhấn kim cương trong vàng trắng.', 8800000, 10200000, 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600', 'Bông tai ngọc trai Tahiti đen kim cương vàng trắng', 'BTE-020', 10, true, false, true, false, 'Vàng trắng 18k, Ngọc trai Tahiti, Kim cương', 4.0, ARRAY['bông tai', 'ngọc trai đen', 'Tahiti', 'kim cương'])
    ON CONFLICT (slug) DO NOTHING;

    -- =====================
    -- LẮC CHÂN (Anklets) - 20 products
    -- =====================
    INSERT INTO public.products (id, category_id, name, name_vi, slug, description, description_vi, price, original_price, image_url, image_alt, sku, stock_quantity, is_active, is_new, is_best_seller, is_featured, material, weight_grams, tags)
    VALUES
    (gen_random_uuid(), cat_lac, 'Gold Anklet', 'Lắc Chân Vàng', 'lac-chan-vang', 'Delicate gold anklet with a simple chain design for everyday wear.', 'Lắc chân vàng tinh tế với thiết kế dây chuyền đơn giản cho việc đeo hàng ngày.', 2800000, 3300000, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', 'Lắc chân vàng tinh tế dây chuyền đơn giản', 'LCC-001', 40, true, false, true, false, 'Vàng vàng 14k', 3.8, ARRAY['lắc chân', 'vàng', 'tinh tế', 'hàng ngày']),
    (gen_random_uuid(), cat_lac, 'Silver Charm Anklet', 'Lắc Chân Charm Bạc', 'lac-chan-charm-bac', 'Playful silver charm anklet with star, moon, and heart charms.', 'Lắc chân charm bạc vui nhộn với charm ngôi sao, mặt trăng và trái tim.', 1200000, 1500000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600', 'Lắc chân charm bạc ngôi sao mặt trăng trái tim', 'LCC-002', 55, true, true, false, false, 'Bạc 925', 2.9, ARRAY['lắc chân', 'charm', 'bạc', 'ngôi sao']),
    (gen_random_uuid(), cat_lac, 'Beaded Turquoise Anklet', 'Lắc Chân Hạt Turquoise', 'lac-chan-hat-turquoise', 'Bohemian beaded anklet with turquoise and silver beads for a beach vibe.', 'Lắc chân hạt phong cách bohemian với hạt turquoise và bạc cho cảm giác bãi biển.', 680000, 850000, 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600', 'Lắc chân hạt turquoise bạc bohemian bãi biển', 'LCC-003', 65, true, true, false, false, 'Bạc 925, Turquoise', 4.2, ARRAY['lắc chân', 'hạt', 'turquoise', 'bãi biển']),
    (gen_random_uuid(), cat_lac, 'Diamond Anklet', 'Lắc Chân Kim Cương', 'lac-chan-kim-cuong', 'Luxurious diamond anklet with brilliant-cut diamonds in white gold.', 'Lắc chân kim cương sang trọng với kim cương cắt brilliant trong vàng trắng.', 18500000, 21500000, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600', 'Lắc chân kim cương brilliant vàng trắng sang trọng', 'LCC-004', 5, true, false, true, true, 'Vàng trắng 18k, Kim cương', 5.5, ARRAY['lắc chân', 'kim cương', 'vàng trắng', 'sang trọng']),
    (gen_random_uuid(), cat_lac, 'Rose Gold Anklet', 'Lắc Chân Vàng Hồng', 'lac-chan-vang-hong', 'Feminine rose gold anklet with a delicate chain and tiny heart charm.', 'Lắc chân vàng hồng nữ tính với dây chuyền tinh tế và charm trái tim nhỏ.', 1950000, 2300000, 'https://images.unsplash.com/photo-'||'1589674781759-c21c37956a44?w=600', 'Lắc chân vàng hồng dây tinh tế charm trái tim', 'LCC-005', 45, true, true, true, false, 'Vàng hồng 14k', 3.1, ARRAY['lắc chân', 'vàng hồng', 'trái tim', 'nữ tính']),
    (gen_random_uuid(), cat_lac, 'Pearl Anklet', 'Lắc Chân Ngọc Trai', 'lac-chan-ngoc-trai', 'Elegant freshwater pearl anklet with gold chain for a sophisticated beach look.', 'Lắc chân ngọc trai nước ngọt thanh lịch với dây vàng cho vẻ ngoài bãi biển tinh tế.', 3200000, 3800000, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600', 'Lắc chân ngọc trai nước ngọt dây vàng', 'LCC-006', 28, true, false, false, false, 'Ngọc trai, Vàng 14k', 4.5, ARRAY['lắc chân', 'ngọc trai', 'vàng', 'bãi biển']),
    (gen_random_uuid(), cat_lac, 'Infinity Anklet', 'Lắc Chân Vô Cực', 'lac-chan-vo-cuc', 'Meaningful infinity symbol anklet in sterling silver with cubic zirconia.', 'Lắc chân biểu tượng vô cực ý nghĩa bằng bạc sterling với cubic zirconia.', 950000, 1200000, 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600', 'Lắc chân vô cực bạc cubic zirconia ý nghĩa', 'LCC-007', 60, true, true, false, false, 'Bạc 925, Cubic Zirconia', 2.7, ARRAY['lắc chân', 'vô cực', 'bạc', 'ý nghĩa']),
    (gen_random_uuid(), cat_lac, 'Sapphire Anklet', 'Lắc Chân Sapphire', 'lac-chan-sapphire', 'Elegant sapphire anklet with blue sapphires set in yellow gold links.', 'Lắc chân sapphire thanh lịch với sapphire xanh được đặt trong mắt xích vàng vàng.', 8900000, 10400000, 'https://images.unsplash.com/photo-1561828995-aa79a2db86dd?w=600', 'Lắc chân sapphire xanh mắt xích vàng vàng', 'LCC-008', 10, true, false, false, false, 'Vàng vàng 18k, Sapphire', 5.8, ARRAY['lắc chân', 'sapphire', 'xanh', 'vàng']),
    (gen_random_uuid(), cat_lac, 'Adjustable Bead Anklet', 'Lắc Chân Hạt Điều Chỉnh', 'lac-chan-hat-dieu-chinh', 'Colorful adjustable bead anklet with natural stone beads for positive energy.', 'Lắc chân hạt điều chỉnh đầy màu sắc với hạt đá tự nhiên mang năng lượng tích cực.', 580000, 750000, 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600', 'Lắc chân hạt điều chỉnh đá tự nhiên màu sắc', 'LCC-009', 80, true, false, false, false, 'Đá tự nhiên', 3.5, ARRAY['lắc chân', 'hạt', 'điều chỉnh', 'đá tự nhiên']),
    (gen_random_uuid(), cat_lac, 'Gold Leaf Anklet', 'Lắc Chân Lá Vàng', 'lac-chan-la-vang', 'Nature-inspired gold leaf anklet with delicate leaf charms on a fine chain.', 'Lắc chân lá vàng lấy cảm hứng từ thiên nhiên với charm lá tinh tế trên dây mảnh.', 2100000, 2500000, 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600', 'Lắc chân lá vàng charm thiên nhiên dây mảnh', 'LCC-010', 35, true, true, false, false, 'Vàng 14k', 3.2, ARRAY['lắc chân', 'lá', 'vàng', 'thiên nhiên']),
    (gen_random_uuid(), cat_lac, 'Crystal Anklet', 'Lắc Chân Pha Lê', 'lac-chan-pha-le', 'Sparkling crystal anklet with Swarovski crystals in a rainbow of colors.', 'Lắc chân pha lê lấp lánh với pha lê Swarovski trong nhiều màu sắc cầu vồng.', 780000, 980000, 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600', 'Lắc chân pha lê Swarovski cầu vồng lấp lánh', 'LCC-011', 70, true, true, false, false, 'Pha lê Swarovski, Bạc 925', 2.8, ARRAY['lắc chân', 'pha lê', 'cầu vồng', 'Swarovski']),
    (gen_random_uuid(), cat_lac, 'Vintage Coin Anklet', 'Lắc Chân Đồng Xu Cổ Điển', 'lac-chan-dong-xu-co-dien', 'Boho vintage coin anklet with hammered gold coins on a delicate chain.', 'Lắc chân đồng xu cổ điển bohemian với đồng xu vàng búa trên dây tinh tế.', 1650000, 2000000, 'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600', 'Lắc chân đồng xu vàng búa bohemian cổ điển', 'LCC-012', 30, true, false, false, false, 'Vàng 14k', 4.8, ARRAY['lắc chân', 'đồng xu', 'cổ điển', 'bohemian']),
    (gen_random_uuid(), cat_lac, 'Emerald Anklet', 'Lắc Chân Emerald', 'lac-chan-emerald', 'Regal emerald anklet with vivid green stones set in yellow gold.', 'Lắc chân emerald sang trọng với đá xanh lá rực rỡ được đặt trong vàng vàng.', 11500000, 13500000, 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600', 'Lắc chân emerald xanh lá vàng vàng sang trọng', 'LCC-013', 7, true, false, true, false, 'Vàng vàng 18k, Emerald', 6.2, ARRAY['lắc chân', 'emerald', 'xanh lá', 'sang trọng']),
    (gen_random_uuid(), cat_lac, 'Butterfly Anklet', 'Lắc Chân Bướm', 'lac-chan-buom', 'Whimsical butterfly anklet with colorful enamel butterfly charms in silver.', 'Lắc chân bướm mộng mơ với charm bướm men màu sắc trong bạc.', 1100000, 1400000, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600', 'Lắc chân bướm men màu sắc bạc mộng mơ', 'LCC-014', 48, true, true, false, false, 'Bạc 925, Men', 3.0, ARRAY['lắc chân', 'bướm', 'men', 'màu sắc']),
    (gen_random_uuid(), cat_lac, 'Opal Anklet', 'Lắc Chân Opal', 'lac-chan-opal', 'Dreamy opal anklet with fire opal stones set in sterling silver.', 'Lắc chân opal mơ mộng với đá opal lửa được đặt trong bạc sterling.', 2400000, 2900000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600', 'Lắc chân opal lửa bạc sterling mơ mộng', 'LCC-015', 22, true, false, false, false, 'Bạc 925, Opal', 3.6, ARRAY['lắc chân', 'opal', 'lửa', 'mơ mộng']),
    (gen_random_uuid(), cat_lac, 'Amethyst Anklet', 'Lắc Chân Amethyst', 'lac-chan-amethyst', 'Calming amethyst anklet with purple stones on a delicate gold chain.', 'Lắc chân amethyst bình yên với đá tím trên dây vàng tinh tế.', 3100000, 3700000, 'https://images.unsplash.com/photo-'||'1603561591411-07134e71a2a9?w=600', 'Lắc chân amethyst tím dây vàng tinh tế', 'LCC-016', 26, true, true, false, false, 'Vàng 14k, Amethyst', 4.1, ARRAY['lắc chân', 'amethyst', 'tím', 'bình yên']),
    (gen_random_uuid(), cat_lac, 'Star Anklet', 'Lắc Chân Ngôi Sao', 'lac-chan-ngoi-sao', 'Celestial star anklet with tiny diamond stars on a fine gold chain.', 'Lắc chân ngôi sao thiên thể với ngôi sao kim cương nhỏ trên dây vàng mảnh.', 4500000, 5300000, 'https://images.unsplash.com/photo-'||'1515562141207-7a88fb7ce338?w=600', 'Lắc chân ngôi sao kim cương dây vàng mảnh', 'LCC-017', 18, true, false, false, false, 'Vàng 14k, Kim cương', 3.4, ARRAY['lắc chân', 'ngôi sao', 'kim cương', 'thiên thể']),
    (gen_random_uuid(), cat_lac, 'Ruby Anklet', 'Lắc Chân Ruby', 'lac-chan-ruby', 'Passionate ruby anklet with deep red rubies in yellow gold for a bold look.', 'Lắc chân ruby đam mê với ruby đỏ đậm trong vàng vàng cho vẻ ngoài nổi bật.', 7200000, 8400000, 'https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=600', 'Lắc chân ruby đỏ vàng vàng nổi bật', 'LCC-018', 11, true, false, true, false, 'Vàng vàng 18k, Ruby', 5.3, ARRAY['lắc chân', 'ruby', 'đỏ', 'nổi bật']),
    (gen_random_uuid(), cat_lac, 'Minimalist Silver Anklet', 'Lắc Chân Bạc Tối Giản', 'lac-chan-bac-toi-gian', 'Ultra-thin minimalist silver anklet, perfect for layering or wearing alone.', 'Lắc chân bạc mỏng tối giản, hoàn hảo để xếp lớp hoặc đeo riêng lẻ.', 650000, NULL, 'https://images.unsplash.com/photo-'||'1596944924616-7b38e7cfac36?w=600', 'Lắc chân bạc mỏng tối giản xếp lớp', 'LCC-019', 90, true, false, false, false, 'Bạc 925', 1.5, ARRAY['lắc chân', 'bạc', 'tối giản', 'mỏng']),
    (gen_random_uuid(), cat_lac, 'Platinum Diamond Anklet', 'Lắc Chân Kim Cương Bạch Kim', 'lac-chan-kim-cuong-bach-kim', 'Ultimate luxury platinum anklet with channel-set diamonds all around.', 'Lắc chân bạch kim sang trọng tối thượng với kim cương đặt kênh xung quanh.', 38000000, 44000000, 'https://images.unsplash.com/photo-'||'1543294001-f7cd5d7fb516?w=600', 'Lắc chân bạch kim kim cương đặt kênh sang trọng', 'LCC-020', 3, true, false, true, true, 'Bạch kim, Kim cương', 8.5, ARRAY['lắc chân', 'bạch kim', 'kim cương', 'sang trọng'])
    ON CONFLICT (slug) DO NOTHING;

EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Sample product insertion failed: %', SQLERRM;
END $$;
